chess_tournament/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('chess_tournament.views',
    url(r'^$', 'home_view', name='home'),
    url(r'^new/$', 'new_tournament_view', name='new_tournament'),
    url(r'^add_player/$', 'add_player', name='add_player'),
    url(r'^create_tournament/$', 'create_tournament', name='create_tournament'),
    url(r'^(?P<tournament_pk>\d+)/$', 'tournament_view', name='tournament'),
    url(r'^set_game_result/(?P<game_pk>\d+)/$', 'set_game_result', name='set_game_result'),

    url(r'^login/$', 'login_view', name='login'),
    url(r'^logout/$', 'logout_view', name='logout'),

    url(r'^admin/', include(admin.site.urls)),
)

chess_tournament/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.db.models import Q
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.templatetags.l10n import localize


class Player(models.Model):
    name = models.CharField(_(u'Имя'), max_length=255)
    rating = models.PositiveIntegerField(_(u'Рейтинг'), db_index=True)

    class Meta:
        ordering = ['-rating']
        verbose_name = _(u'Игрок')
        verbose_name_plural = _(u'Игроки')

    def __unicode__(self):
        return self.name

    def add_rating(self, add):
        self.rating += add
        if self.rating < 0:
            self.rating = 0
        self.save()


class Tournament(models.Model):
    date = models.DateField(_(u'Дата начала турнира'), auto_now_add=True)
    players = models.ManyToManyField(Player, verbose_name=_(u'Участники'), through='PlayerScore')
    ended = models.BooleanField(_(u'Закончен'), default=False)

    class Meta:
        ordering = ['-pk']
        verbose_name = _(u'Турнир')
        verbose_name_plural = _(u'Турниры')

    def __unicode__(self):
        return localize(self.date)

    def get_absolute_url(self):
        return reverse('tournament', args=(self.pk,))

    @classmethod
    def start(cls, player_ids):
        players = Player.objects.filter(pk__in=player_ids)

        if players.count() < 2:
            return None

        tournament = cls.objects.create()

        for player in players:
            PlayerScore.objects.create(player=player, tournament=tournament)

        tournament.new_round()

        return tournament

    def new_round(self):
        n_rounds = self.rounds.all().count()
        if n_rounds < settings.MAX_ROUNDS_NUMBER:
            Round.objects.create(
                number=n_rounds + 1,
                tournament=self,
            ).check_games()
        else:
            self.end()

    def end(self):
        self.ended = True
        self.save()


class PlayerScore(models.Model):
    player = models.ForeignKey(Player)
    tournament = models.ForeignKey(Tournament, related_name='scores')
    score = models.FloatField(_(u'Очки'), default=0, db_index=True)

    class Meta:
        ordering = ['-score']
        verbose_name = _(u'Очки')
        verbose_name_plural = _(u'Очки')

    def __unicode__(self):
        return u'{} {}'.format(self.player, self.score)


class Round(models.Model):
    number = models.PositiveIntegerField(_(u'Номер тура'), db_index=True)
    tournament = models.ForeignKey(Tournament, verbose_name=_(u'Турнир'), related_name='rounds')

    class Meta:
        ordering = ['-number']
        verbose_name = _(u'Тур')
        verbose_name_plural = _(u'Туры')

    def __unicode__(self):
        return unicode(self.number)

    def check_games(self):
        if not self.games.exists():
            # Создать пары игроков
            scores = self.tournament.scores.all().select_related('player')
            players = [score.player for score in scores]
            found_pair = []
            without_pair = []

            for i, a in enumerate(players):
                if a in found_pair:
                    continue

                for b in players[i + 1:]:
                    if b in found_pair:
                        continue

                    if not Game.objects.filter(
                        Q(white=a, black=b) |
                        Q(black=a, white=b),
                        tournament=self.tournament,
                    ).exists():
                        # За белых играет тот, кто провел ими меньше игр в турнире
                        a_white = Game.objects.filter(
                            tournament=self.tournament,
                            white=a,
                        ).count()
                        b_white = Game.objects.filter(
                            tournament=self.tournament,
                            white=b,
                        ).count()

                        if a_white > b_white:
                            white, black = b, a
                        else:
                            white, black = a, b

                        Game.objects.create(
                            tournament=self.tournament,
                            round=self,
                            white=white,
                            black=black,
                        )
                        found_pair.append(a)
                        found_pair.append(b)
                        break
                else:
                    without_pair.append(a)

            if len(without_pair) == 1:
                # Последнему дается очко
                s = PlayerScore.objects.get(
                    player=without_pair[0],
                    tournament=self.tournament,
                )
                s.score += 1
                s.save()
            elif len(without_pair) > 1:
                # Конец турнира
                self.games.all().delete()
                self.delete()
                self.tournament.end()

        elif not self.games.filter(result='pending').exists():
            # Все игры текущего раунда закончены
            self.tournament.new_round()


class Game(models.Model):
    GAME_RESULT = (
        ('pending', _(u'Ожидается')),
        ('white', _(u'Победа белых')),
        ('black', _(u'Победа черных')),
        ('draw', _(u'Ничья')),
    )

    ADD_POINTS = {
        'white': (1, 0),
        'black': (0, 1),
        'draw': (0.5, 0.5),
    }

    tournament = models.ForeignKey(Tournament, verbose_name=_(u'Турнир'), related_name='games')
    round = models.ForeignKey(Round, verbose_name=_(u'Тур'), related_name='games')
    white = models.ForeignKey(Player, verbose_name=_(u'Игрок белыми'), related_name='white_games')
    black = models.ForeignKey(Player, verbose_name=_(u'Игрок черными'), related_name='black_games')
    result = models.CharField(_(u'Результат'), choices=GAME_RESULT, default='pending', max_length=7)

    class Meta:
        ordering = ['pk']
        verbose_name = _(u'Игра')
        verbose_name_plural = _(u'Игры')

    def __unicode__(self):
        return u'{} : {} - {}'.format(self.white, self.black, self.result)

    def set_result(self, result):
        """Указать результат игры"""

        if result in [
            'white',
            'black',
            'draw',
        ] and self.result == 'pending':
            # Сохранить результат игры
            self.result = result
            self.save()

            # Изменить очки игроков
            white_points, black_points = self.ADD_POINTS[result]
            self.add_points(self.white, white_points)
            self.add_points(self.black, black_points)

            # Пересчитать рейтинг игроков
            white_rating = self.compute_rating(self.white, self.black, white_points)
            black_rating = self.compute_rating(self.black, self.white, black_points)
            self.white.add_rating(white_rating)
            self.black.add_rating(black_rating)

            self.round.check_games()
            return True

        return False

    def add_points(self, player, points):
        if points:
            score = PlayerScore.objects.get(
                tournament=self.round.tournament,
                player=player,
            )
            score.score += points
            score.save()

    def compute_rating(self, player, opponent, points):
        """Изменение рейтинга Эло"""
        E = 1.0 / (1 + 10 ** (float(opponent.rating - player.rating) / 400))
        K = 10 if player.rating >= 2400 else 15
        return K * (points - E)

chess_tournament/views.py
# -*- coding: utf-8 -*-

import json

from django.contrib import messages
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.views.decorators.csrf import csrf_protect
from django.utils.translation import ugettext_lazy as _

from chess_tournament.models import Tournament, Player, Game


def home_view(request):
    """Главная страница сайта со списком турниров"""

    tournaments = Tournament.objects.prefetch_related('scores__player', 'rounds')

    for t in tournaments:
        t.top_scores = t.scores.all()[:3]
        t.current_round = t.rounds.all().first().number

    return render(
        request,
        'chess_tournament/home.html',
        {'tournaments': tournaments},
    )


@login_required
def new_tournament_view(request):
    """Страница выбора игроков для нового турнира"""

    return render(
        request,
        'chess_tournament/new.html',
        {'players': Player.objects.all()},
    )


@login_required
def add_player(request):
    """Создает игрока"""
    if request.method == 'POST':
        rating = request.POST.get('rating', '')
        name = request.POST.get('name', '')

        if rating.isdigit() and name:
            player = Player.objects.create(
                rating=int(rating),
                name=name,
            )
            return HttpResponse(json.dumps({
                'player_pk': player.pk,
                'rating': rating,
                'name': name,
            }))

    return HttpResponseBadRequest()


@login_required
def create_tournament(request):
    """Создание турнира"""

    if request.method == 'POST':
        players = request.POST.getlist('players')
        players = [int(player) for player in players if player.isdigit()]

        tournament = Tournament.start(players)

        if tournament is not None:
            return redirect(tournament.get_absolute_url())
        else:
            messages.add_message(request, messages.ERROR, _(u'Не удалось создать турнир'))

    return redirect('new_tournament')


def tournament_view(request, tournament_pk):
    """Страница турнира"""

    t = get_object_or_404(Tournament, pk=tournament_pk)
    t.all_scores = t.scores.all().select_related('player')
    t.all_rounds = t.rounds.all().prefetch_related('games')

    return render(
        request,
        'chess_tournament/tournament.html',
        {'tournament': t},
    )


@login_required
def set_game_result(request, game_pk):
    """Ввод результата игры"""

    game = get_object_or_404(Game, pk=game_pk)
    result = request.POST.get('result', '')

    if request.method != 'POST' or not game.set_result(result):
        messages.add_message(request, messages.ERROR, _(u'Не удалось сохранить результат игры'))

    return redirect(game.round.tournament.get_absolute_url())


@csrf_protect
@never_cache
def login_view(request):
    if request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')

        user = authenticate(username=username, password=password)

        if user and user.is_active:
            login(request, user)
        else:
            messages.add_message(request, messages.ERROR, _(u'Неправильный логин или пароль'))

    return redirect(request.META.get('HTTP_REFERER', 'home'))


def logout_view(request):
    logout(request)
    return redirect(request.META.get('HTTP_REFERER', 'home'))

chess_tournament/templates/chess_tournament/base.html
{% load i18n %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <title>{% block title %}{% trans "Шахматный турнир" %}{% endblock %}</title>
    <meta charset="utf-8"> 
    <link href="/static/img/favicon.png" rel="icon" type="image/png">
    <link href="/static/css/bootstrap.css" rel="stylesheet">
    <script src="/static/js/jquery-2.1.1.js"></script>
    <script src="/static/js/bootstrap.js"></script>
    {% block head %}{% endblock %}
  </head>
  <body>
    <div class="navbar navbar-default" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url "home" %}">{% trans "Шахматный турнир" %}</a>
        </div>
        <div class="navbar-collapse collapse">
          {% if user.is_authenticated %}
            <ul class="nav navbar-nav navbar-right">
              <li class="active dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <span class="glyphicon glyphicon-user"></span> {{ user.username }} <span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="{% url "logout" %}">{% trans "Выйти" %}</a></li>
                </ul>
              </li>
            </ul>
          {% else %}
            <form class="navbar-form navbar-right" role="form" action="{% url "login" %}" method="post">
              {% csrf_token %}
              <div class="form-group">
                <input type="text" placeholder="{% trans "Логин" %}" class="form-control" name="username">
                <input type="password" placeholder="{% trans "Пароль" %}" class="form-control" name="password">
                <button type="submit" class="btn btn-success">{% trans "Войти" %}</button>
              </div>
            </form>
          {% endif %}
        </div>
      </div>
    </div>
    <div class="container">
      {% if messages %}
        {% for message in messages %}
          <div class="alert{% if "error" in message.tags %} alert-danger{% else %} alert-info{% endif %}">{{ message|safe }}</div>
        {% endfor %}
      {% endif %}
      {% block content %}{% endblock %}
      <div class="row">
        <div class="col-xs-12">
          <footer>
            © Больжатов Сергей 2014
          </footer>
          <br>
        </div>
      </div>
    </div>
  </body>
</html>

chess_tournament/templates/chess_tournament/home.html
{% extends "chess_tournament/base.html" %}
{% load i18n %}

{% block content %}

{% if user.is_authenticated %}
  <div class="row">
    <div class="col-xs-12">
      <a href="{% url "new_tournament" %}" class="btn btn-success btn-lg pull-right " role="button">
        {% trans "Провести турнир" %} <span class="glyphicon glyphicon-chevron-right"></span>
      </a>
    </div>
  </div>
{% endif %}

{% for tournament in tournaments %}
  <div class="col-xs-6">
    <h2>
      <a href="{{ tournament.get_absolute_url }}">{{ tournament }}</a>
      <span class="pull-right">
        {% if tournament.ended %}
          <span class="glyphicon glyphicon-tower" title="{% trans "Турнир окончен" %}"></span>
        {% endif %}
        {{ tournament.current_round }} {% trans "тур" %}
      </span>
    </h2>
    <ul class="list-group">
    {% for score in tournament.top_scores %}
      <li class="list-group-item">
        {{ score.player }}
        <span class="badge">{{ score.score }}</span>
        <span class="badge pull-left">{{ score.player.rating }}</span>
      </li>
    {% endfor %}
    </ul>
  </div>
{% endfor %}

{% endblock %}

chess_tournament/templates/chess_tournament/new.html
{% extends "chess_tournament/base.html" %}
{% load i18n %}

{% block title %}{% trans "Новый турнир"%}{% endblock %}
{% block head %}
  <script src="/static/js/new.js"></script>
{% endblock %}

{% block content %}

<h1>{% trans "Выберите игроков" %}</h1>

<div class="row">
  <div class="col-xs-5">
    <table class="table" id="all_players" style="cursor: pointer">
      {% for player in players %}
        <tr player_pk="{{ player.pk }}">
          <td>{{ player.rating }}</td>
          <td>{{ player.name }}</td>
          <td><span class="glyphicon glyphicon-resize-horizontal"></span></td>
        </tr>
      {% endfor %}
    </table>
  </div>
  <div class="col-xs-2">
    <h1 class="text-center"><span class="glyphicon glyphicon-chevron-right"></span></h1>
  </div>
  <div class="col-xs-5">
    <table class="table" id="tournament_players" style="cursor: pointer">
    </table>
    <form class="form-inline" id="new_player_form">
      {% csrf_token %}
      <div class="form-group">
        <input type="number" name="rating" pattern="\d+" min="0" class="form-control visible" placeholder="{% trans "Рейтинг" %}">
      </div>
      <div class="form-group">
        <input type="text" name="name" class="form-control visible" placeholder="{% trans "Имя" %}">
      </div>
      <button type="submit" class="btn btn-primary">{% trans "Добавить" %}</button>
    </form>
  </div>
</div>

<br>

<div class="pull-right">
  <form action="{% url "create_tournament" %}" method="post" id="create_tournament_form">
    {% csrf_token %}
    <button class="btn btn-success btn-lg disabled" type="submit" id="create_tournament_button">
      {% trans "Начать турнир" %} <span class="glyphicon glyphicon-chevron-right"></span>
    </button>
    <select name="players" multiple="multiple" id="create_tournament_select" style="display: none">
    </select>
  </form>
</div>

{% endblock %}

chess_tournament/templates/chess_tournament/tournament.html
{% extends "chess_tournament/base.html" %}
{% load i18n %}

{% block title %}{{ tournament }}{% endblock %}
{% block head %}
  <script src="/static/js/tournament.js"></script>
{% endblock %}

{% block content %}
<h2>{{ tournament }}</h2>
<div class="row">
  <div class="col-xs-6">
    <ul class="list-group">
    {% for score in tournament.all_scores %}
      <li class="list-group-item">
        {{ score.player }}
        <span class="badge">{{ score.score }}</span>
        <span class="badge pull-left">{{ score.player.rating }}</span>
      </li>
    {% endfor %}
    </ul>
  </div>

{% for round in tournament.all_rounds %}
  {% if not forloop.counter0|divisibleby:2 %}
    <div class="row">
  {% endif %}
  <div class="col-xs-6">
    <h3>{{ round.number }} {% trans "тур" %}</h3>
    <table class="table">
      <tr>
        <th>{% trans "Белые" %}</td>
        <th></td>
        <th>{% trans "Черные" %}</td>
      </tr>
      {% for game in round.games.all %}
        <tr>
          <td>{{ game.white }}</td>
          {% if game.result == 'pending' and user.is_authenticated %}
            <td>
              <div class="input-group">
                <select game_pk="{{ game.pk }}" class="result_selector form-control input-sm">
                  <option value="pending" selected="selected">{% trans "Ожидается" %}</option>
                  <option value="white">{% trans "Победа белых" %}</option>
                  <option value="black">{% trans "Победа черных" %}</option>
                  <option value="draw">{% trans "Ничья" %}</option>
                </select>
              </div>
            </td>
          {% else %}
            <td>{{ game.get_result_display }}</td>
          {% endif %}
          <td>{{ game.black }}</td>
        </tr>
      {% endfor %}
    </table>
  </div>
  {% if forloop.counter0|divisibleby:2 or forloop.last %}
    </div><!-- div class="row" -->
  {% endif %}
{% endfor %}

<form method="post" id="set_game_result_form">
  {% csrf_token %}
  <select name="result" id="set_game_result_select" style="display: none"></select>
</form>

{% endblock %}